# Generated by Django 5.1.5 on 2025-03-29 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', 'sync_admin_roles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learningpathway',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='learning_pathway',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='date_deactivated',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='last_login_ip',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='profile_picture',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='role',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='expected_output',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='is_published',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='lessonfeedback',
            name='ai_feedback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lessonfeedback',
            name='code',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lessonfeedback',
            name='feedback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='AdminActivityLog',
        ),
        migrations.DeleteModel(
            name='LearningPathway',
        ),
    ]
