# Generated by Django 5.1.5 on 2025-06-28 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_remove_learningpathway_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='expected_output',
            field=models.TextField(blank=True, null=True),
        ),
    ]
