# Generated by Django 5.1.5 on 2025-06-29 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_lesson_expected_output'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='solution',
            field=models.TextField(blank=True, null=True),
        ),
    ]
