# Generated by Django 5.1.5 on 2025-02-01 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_studysession_completed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studysession',
            name='title',
        ),
        migrations.AddField(
            model_name='studysession',
            name='lesson',
            field=models.CharField(default='Untitled Lesson', max_length=255),
        ),
    ]
