# Generated by Django 5.1.5 on 2025-07-06 20:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_quizquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprogress',
            name='xp',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='lesson',
            field=models.ForeignKey(blank=True, help_text='Leave blank for global quiz questions', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quiz_questions', to='accounts.lesson'),
        ),
    ]
