# Generated by Django 5.1.5 on 2025-02-01 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_studysession_title_studysession_lesson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studysession',
            name='lesson',
            field=models.CharField(max_length=255),
        ),
    ]
