# Generated by Django 5.1.5 on 2025-07-06 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_userprogress_xp_alter_quizquestion_lesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprogress',
            name='level',
            field=models.IntegerField(default=1),
        ),
    ]
