# Generated by Django 5.1.5 on 2025-07-06 22:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_userprogress_level'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quizquestion',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='order',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='lesson',
            field=models.ForeignKey(blank=True, help_text='Leave blank for global quiz questions', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='accounts.lesson'),
        ),
    ]
