# Generated by Django 5.1.5 on 2025-02-02 00:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_studysession_lesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='studysession',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studysession',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studysession',
            name='learning_goal',
            field=models.CharField(default='Beginner', max_length=100),
        ),
        migrations.AlterField(
            model_name='studysession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_sessions', to=settings.AUTH_USER_MODEL),
        ),
    ]
