# Generated by Django 5.1.5 on 2025-07-08 02:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_quizquestion_options_quizquestion_order_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz_type', models.CharField(max_length=50)),
                ('best_score', models.PositiveIntegerField(default=0)),
                ('total_questions', models.PositiveIntegerField(default=5)),
                ('max_xp_earned', models.PositiveIntegerField(default=0)),
                ('learning_goal', models.CharField(max_length=100)),
                ('difficulty_level', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'quiz_type', 'learning_goal', 'difficulty_level')},
            },
        ),
    ]
