# Generated by Django 5.1.5 on 2025-02-02 00:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_studysession_completed_studysession_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studysession',
            name='learning_goal',
        ),
        migrations.AlterField(
            model_name='studysession',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.lesson'),
        ),
        migrations.AlterField(
            model_name='studysession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
