# Generated by Django 5.1.5 on 2025-02-02 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_studysession_learning_goal_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studysession',
            name='completed',
        ),
        migrations.RemoveField(
            model_name='studysession',
            name='description',
        ),
    ]
