# Generated by Django 5.1.5 on 2025-02-02 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_remove_studysession_completed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studysession',
            name='learning_goal',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
