# Generated by Django 5.1.5 on 2025-07-08 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_useractivity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractivity',
            name='activity_type',
            field=models.CharField(choices=[('lesson_completed', 'Lesson Completed'), ('quiz_passed', 'Quiz Passed'), ('streak_milestone', 'Streak Milestone'), ('level_up', 'Level Up'), ('xp_earned', 'XP Earned'), ('account_created', 'Account Created'), ('study_session_added', 'Study Session Added')], max_length=25),
        ),
    ]
